# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
x1 = np.random.randint(20, size=6)  
x2 = np.random.randint(10, size=(3, 4)) 
print(x1)
print(x2)

# Create a 2-dimensional NumPy array using np.array()
  

[ 0 13  8  0 15  6]
[[8 8 1 3]
 [7 8 3 2]
 [3 5 2 7]]


In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("shape :",x1.shape,"     " ,"number of dimension:",x1.ndim ,"    ","data type :",x1.dtype,"      ","size:",x1.size )




shape : (6,)       number of dimension: 1      data type : int32        size: 6


In [4]:
# Attributes of 2-dimensional array
print("shape :",x2.shape,"     " ,"number of dimension:",x2.ndim ,"    ","data type :",x2.dtype,"      ","size:",x2.size )

shape : (3, 4)       number of dimension: 2      data type : int32        size: 12


In [5]:
# Create an array of shape (5, 5) with only ones
np.ones([ 5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros([3,3,5] ,dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[6, 4],
       [6, 7],
       [7, 8],
       [9, 8],
       [0, 1],
       [1, 2],
       [7, 0]])

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.33013383, 0.31735378, 0.13415534, 0.80012983, 0.59492086],
       [0.06463964, 0.16394009, 0.30693895, 0.80901921, 0.89644856],
       [0.64834729, 0.77452629, 0.62972878, 0.35265162, 0.02373947]])

In [9]:
# Create an array of normally distributed random numbers

np.random.normal(size=(int(input()),int(input())))

 5
 6


array([[-0.41593496, -0.31870365, -1.52788935,  0.42351633,  0.35579818,
        -0.45609022],
       [-2.24575115,  1.23121722, -0.66690627, -0.80958681, -2.43638098,
         0.57248564],
       [ 0.72539892,  0.45435039, -0.29819123,  0.21400964,  0.33114121,
         1.62283893],
       [-0.02980656, -0.05012857, -1.23840655, -0.28717937,  1.28500247,
        -1.30669366],
       [ 0.26203664,  0.62905444, -0.67418758,  0.94285429, -0.1151744 ,
        -0.38460322]])

In [10]:
# Set the random seed to 42
import random
random.seed(45)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size=(4,6))

array([[6, 1, 7, 6, 0, 2],
       [0, 1, 8, 5, 3, 8],
       [1, 3, 9, 1, 1, 7],
       [6, 7, 3, 6, 3, 2]])

In [11]:
# Copy the code from the cell above and run it again
import random
random.seed(45)


p=np.random.randint(10,size=(4,6))
p

array([[9, 0, 8, 3, 9, 0],
       [6, 3, 4, 9, 8, 4],
       [8, 5, 5, 9, 3, 8],
       [9, 1, 4, 2, 4, 3]])

In [12]:
# Find the 0'th index of the latest array you created
p[0][0]

9

In [13]:
# Get the first 2 rows of latest array you created
p[2:]

array([[8, 5, 5, 9, 3, 8],
       [9, 1, 4, 2, 4, 3]])

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
p[:2,:2]


array([[9, 0],
       [6, 3]])

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
r1,r2=np.random.randint(10, size=(3,5)),np.ones( [3,5])


In [16]:
# Add the two arrays together
r1+r2

array([[10.,  7.,  7.,  1., 10.],
       [ 1.,  1.,  4.,  2.,  7.],
       [ 6.,  9.,  7.,  7., 10.]])

In [17]:
# Create another array of ones of shape (5, 3)
r3=np.ones( [5,3])
r3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
r3+r1+r2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [22]:
# Do the same operation you just did but this time with a transpose on one array
rn=r3.transpose()
rr=rn+r1+r2
rr

array([[11.,  8.,  8.,  2., 11.],
       [ 2.,  2.,  5.,  3.,  8.],
       [ 7., 10.,  8.,  8., 11.]])

In [23]:
# Take the latest array to the power of 2 using the python way
rr**2

array([[121.,  64.,  64.,   4., 121.],
       [  4.,   4.,  25.,   9.,  64.],
       [ 49., 100.,  64.,  64., 121.]])

In [24]:
# Do the same thing with numpy way
np.square(rr)

array([[121.,  64.,  64.,   4., 121.],
       [  4.,   4.,  25.,   9.,  64.],
       [ 49., 100.,  64.,  64., 121.]])

In [25]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print("mean =",np.mean(rr),"     ","min = ",np.min(rr),"    ","max = ",np.max(rr),"    ","standard deviation = ", np.sqrt(np.mean((rr - np.mean(rr)) ** 2 )),"     ","variance = ",np.mean((rr - np.mean(rr)) ** 2 ))


mean = 6.933333333333334       min =  2.0      max =  11.0      standard deviation =  3.2345358588555206       variance =  10.462222222222222


In [26]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
ar1,ar2=np.random.randint(10, size=(3,3)),np.random.randint(10, size=(3,2))

In [27]:
# Perform a dot product on the two newest arrays you created

ar1.dot(ar2)

array([[109,  78],
       [108,  85],
       [102,  68]])

In [28]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
arr1 ,arr2=np.random.randint(10, size=(4,3)),np.random.randint(10, size=(4,3))

In [29]:
# Perform a hadamard product on the two newest arrays you created
np.multiply( arr1,arr2)

array([[24, 18,  0],
       [20,  0, 24],
       [54, 15, 30],
       [27, 24, 21]])

In [30]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(arr1,arr2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [31]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(arr1,arr2.T)

array([[ 42,  43,  72,  57],
       [ 32,  44,  60,  30],
       [ 81,  71,  99,  60],
       [ 84,  81, 116,  72]])

In [32]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
A,B=np.random.randint(10, size=(3,4)),np.random.randint(10, size=(3,4))

In [33]:
# Compare the two arrays with '>', '<=' and '==' 
print(A>B)
print(A<=B)
print(A==B)

[[False  True  True False]
 [ True  True False False]
 [False False  True False]]
[[ True False False  True]
 [False False  True  True]
 [ True  True False  True]]
[[False False False  True]
 [False False  True False]
 [False False False False]]


In [34]:
# Sort one of the arrays you just created in ascending order
np.sort(A)

array([[1, 6, 7, 8],
       [3, 3, 5, 6],
       [1, 4, 7, 7]])

In [35]:
# Sort the indexes of one of the arrays you just created
np.argsort(B)

array([[2, 1, 0, 3],
       [0, 1, 2, 3],
       [2, 1, 3, 0]], dtype=int64)

In [36]:
# Find the index with the maximum value in one of the arrays you've created


np.where(A == np.max(A))

(array([0], dtype=int64), array([1], dtype=int64))

In [37]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
#p=np.array([[1,2,3],[4,3,1]])
np.argmax(A,axis=1)

array([1, 0, 0], dtype=int64)

In [52]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmax(A,axis=0)

array([2, 0, 2, 0], dtype=int64)